### ISSUE TITLE
Add / Actualize readme files explaining folders source code.

### ISSUE THREAD

**Issue by aleksmelnikov** [ALTIBASE/altibase#53]
Please, could you add/actualize readme files explaining folders source code. 
It will be great for explore it.

## Todo

- [ ] src/cm: add readme
- [ ] src/core: add readme
- [ ] src/dk: add readme
- [ ] src/id: add readme
- [ ] src/mm: actualize readme
- [ ] src/mt: actualize readme
- [ ] src/pd: actualize readme
- [ ] src/qp: actualize readme
- [ ] src/rp: actualize readme
- [ ] src/sd: actualize readme
- [ ] src/sm: actualize readme
- [ ] src/st: actualize readme
- [ ] src/ul: add readme
